# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
service: api-ices-me
frameworkVersion: '3'
useDotenv: true
custom:
  dynamodb:
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
    stages:
      - ${env:STAGE}
  secrets: ${file(secrets.json)}
provider:
  name: aws
  runtime: nodejs12.x
  region: ${env:AWS_APP_REGION}
  environment:
    REGION: "${self:provider.region}"
    JWT_SECRET: ${self:custom.secrets.JWT_SECRET}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${env:AWS_APP_REGION}:*:*"

functions:
  - ${file(functions/auth/_functions.yml)}
  - ${file(functions/articles/_functions.yml)}
  - ${file(functions/categories/_functions.yml)}
  - ${file(functions/me/_functions.yml)}
plugins:
  - serverless-dynamodb-local
  - serverless-offline
  - serverless-dotenv-plugin
resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: UsersTable
        AttributeDefinitions:
          - AttributeName: email
            AttributeType: S
        KeySchema:
          - AttributeName: email
            KeyType: HASH
#        BillingMode: PAY_PER_REQUEST
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    CategoriesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: CategoriesTable
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
#        BillingMode: PAY_PER_REQUEST
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    PostsTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: PostsTable
        AttributeDefinitions:
          - AttributeName: title
            AttributeType: S
        KeySchema:
          - AttributeName: title
            KeyType: HASH
#        BillingMode: PAY_PER_REQUEST
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1